-- Generated from read-only Pipedrive field metadata. No writes to Pipedrive.

alter table public.custom_fields add column if not exists pipedrive_key text;
alter table public.custom_fields add column if not exists pipedrive_field_type text;
alter table public.custom_fields add column if not exists pipedrive_id int;
alter table public.custom_fields add column if not exists pipedrive_options jsonb not null default '[]'::jsonb;

create unique index if not exists custom_fields_entity_pipedrive_key_idx
  on public.custom_fields(entity, pipedrive_key)
  where pipedrive_key is not null;

with pipedrive_fields(entity, name, field_type, options, sort_order, pipedrive_key, pipedrive_field_type, pipedrive_id, pipedrive_options) as (
  values
    ('deal', 'ID', 'numeric', '{}'::text[], 1, 'id', 'int', 12477, '[]'::jsonb),
    ('deal', 'Title', 'text', '{}'::text[], 2, 'title', 'varchar', 12453, '[]'::jsonb),
    ('deal', 'Creator', 'user_ref', '{}'::text[], 3, 'creator_user_id', 'user', 12454, '[]'::jsonb),
    ('deal', 'Owner', 'user_ref', '{}'::text[], 4, 'user_id', 'user', 12455, '[]'::jsonb),
    ('deal', 'Weighted value', 'monetary', '{}'::text[], 5, 'weighted_value', 'monetary', 12457, '[]'::jsonb),
    ('deal', 'Currency of Weighted value', 'text', '{}'::text[], 6, 'weighted_value_currency', 'varchar', null, '[]'::jsonb),
    ('deal', 'Pipeline', 'numeric', '{}'::text[], 7, 'pipeline', 'double', 12460, '[]'::jsonb),
    ('deal', 'Stage', 'single_option', '{}'::text[], 8, 'stage_id', 'stage', 12462, '[]'::jsonb),
    ('deal', 'Status', 'single_option', array['Open', 'Lost', 'Won', 'Deleted']::text[], 9, 'status', 'status', 12464, '[{"id": "open", "label": "Open"}, {"id": "lost", "label": "Lost"}, {"id": "won", "label": "Won"}, {"id": "deleted", "label": "Deleted"}]'::jsonb),
    ('deal', 'Deal created', 'date', '{}'::text[], 10, 'add_time', 'date', 12465, '[]'::jsonb),
    ('deal', 'Update time', 'date', '{}'::text[], 11, 'update_time', 'date', 12466, '[]'::jsonb),
    ('deal', 'Last stage change', 'date', '{}'::text[], 12, 'stage_change_time', 'date', 12467, '[]'::jsonb),
    ('deal', 'Next activity date', 'date', '{}'::text[], 13, 'next_activity_date', 'date', 12468, '[]'::jsonb),
    ('deal', 'Last activity date', 'date', '{}'::text[], 14, 'last_activity_date', 'date', 12469, '[]'::jsonb),
    ('deal', 'Won time', 'date', '{}'::text[], 15, 'won_time', 'date', 12470, '[]'::jsonb),
    ('deal', 'Last email received', 'date', '{}'::text[], 16, 'last_incoming_mail_time', 'date', 12471, '[]'::jsonb),
    ('deal', 'Last email sent', 'date', '{}'::text[], 17, 'last_outgoing_mail_time', 'date', 12472, '[]'::jsonb),
    ('deal', 'Lost time', 'date', '{}'::text[], 18, 'lost_time', 'date', 12473, '[]'::jsonb),
    ('deal', 'Deal closed on', 'date', '{}'::text[], 19, 'close_time', 'date', 12474, '[]'::jsonb),
    ('deal', 'Motivo da perda', 'single_option', array['[FUP SDR] Quer que entre em contato depois', '[FUP SDR] Não tem interesse', '[FUP SDR] Não quer ser mais contatado', '[FUP SDR] 10 TPs sem resposta', 'Pessoa Física - Lead Desqualificado', 'Nao tem perfil de cliente - Lite ( Vendas )', 'Orçamento Incompatível ( Vendas )', 'Não enxergou valor na Proposta ( Vendas )', 'Cliente sumiu / Falta de Follow Up ( Vendas ou Pos venda )', 'Perfil Shop', 'Erro na plataforma ( Pos venda)', 'Insatisfacao por atendimento ( Pos venda )', 'Falta de funcionalidade ( Pos venda )', 'Fechamento da unidade ( Pos venda )', 'CS - Sem uso']::text[], 20, 'lost_reason', 'varchar_options', 12475, '[{"id": 238, "label": "[FUP SDR] Quer que entre em contato depois"}, {"id": 236, "label": "[FUP SDR] Não tem interesse"}, {"id": 235, "label": "[FUP SDR] Não quer ser mais contatado"}, {"id": 234, "label": "[FUP SDR] 10 TPs sem resposta"}, {"id": 232, "label": "Pessoa Física - Lead Desqualificado"}, {"id": 61, "label": "Nao tem perfil de cliente - Lite ( Vendas )"}, {"id": 62, "label": "Orçamento Incompatível ( Vendas )"}, {"id": 63, "label": "Não enxergou valor na Proposta ( Vendas )"}, {"id": 64, "label": "Cliente sumiu / Falta de Follow Up ( Vendas ou Pos venda )"}, {"id": 224, "label": "Perfil Shop"}, {"id": 65, "label": "Erro na plataforma ( Pos venda)"}, {"id": 66, "label": "Insatisfacao por atendimento ( Pos venda )"}, {"id": 88, "label": "Falta de funcionalidade ( Pos venda )"}, {"id": 89, "label": "Fechamento da unidade ( Pos venda )"}, {"id": 90, "label": "CS - Sem uso"}]'::jsonb),
    ('deal', 'Visible to', 'single_option', array['Item owner', 'All users']::text[], 21, 'visible_to', 'visible_to', 12476, '[{"id": 1, "label": "Item owner"}, {"id": 3, "label": "All users"}]'::jsonb),
    ('deal', 'Total activities', 'numeric', '{}'::text[], 22, 'activities_count', 'int', 12478, '[]'::jsonb),
    ('deal', 'Done activities', 'numeric', '{}'::text[], 23, 'done_activities_count', 'int', 12479, '[]'::jsonb),
    ('deal', 'Activities to do', 'numeric', '{}'::text[], 24, 'undone_activities_count', 'int', 12480, '[]'::jsonb),
    ('deal', 'Email messages count', 'numeric', '{}'::text[], 25, 'email_messages_count', 'int', 12481, '[]'::jsonb),
    ('deal', 'Product quantity', 'numeric', '{}'::text[], 26, 'product_quantity', 'double', 12482, '[]'::jsonb),
    ('deal', 'Product amount', 'numeric', '{}'::text[], 27, 'product_amount', 'double', 12483, '[]'::jsonb),
    ('deal', 'Product name', 'text', '{}'::text[], 28, 'product_name', 'varchar', 12495, '[]'::jsonb),
    ('deal', 'MRR', 'monetary', '{}'::text[], 29, 'mrr', 'monetary', 12501, '[]'::jsonb),
    ('deal', 'Currency of MRR', 'text', '{}'::text[], 30, 'mrr_currency', 'varchar', null, '[]'::jsonb),
    ('deal', 'ARR', 'monetary', '{}'::text[], 31, 'arr', 'monetary', 12502, '[]'::jsonb),
    ('deal', 'Currency of ARR', 'text', '{}'::text[], 32, 'arr_currency', 'varchar', null, '[]'::jsonb),
    ('deal', 'ACV', 'monetary', '{}'::text[], 33, 'acv', 'monetary', 12503, '[]'::jsonb),
    ('deal', 'Currency of ACV', 'text', '{}'::text[], 34, 'acv_currency', 'varchar', null, '[]'::jsonb),
    ('deal', 'Source origin', 'single_option', array['Manually created', 'Import', 'API', 'Automation', 'Marketplace', 'Prospector', 'Lead suggestions', 'Web Forms', 'Chatbot', 'Live Chat', 'Web Visitors', 'Campaigns', 'Messaging inbox']::text[], 35, 'origin', 'enum', 12504, '[{"id": "ManuallyCreated", "label": "Manually created"}, {"id": "Import", "label": "Import"}, {"id": "API", "label": "API"}, {"id": "Automation", "label": "Automation"}, {"id": "Marketplace", "label": "Marketplace"}, {"id": "Prospector", "label": "Prospector"}, {"id": "LeadSuggestion", "label": "Lead suggestions"}, {"id": "WebForms", "label": "Web Forms"}, {"id": "Chatbot", "label": "Chatbot"}, {"id": "LiveChat", "label": "Live Chat"}, {"id": "WebVisitors", "label": "Web Visitors"}, {"id": "Campaigns", "label": "Campaigns"}, {"id": "MessagingInbox", "label": "Messaging inbox"}]'::jsonb),
    ('deal', 'Source origin ID', 'text', '{}'::text[], 36, 'origin_id', 'varchar', 12505, '[]'::jsonb),
    ('deal', 'Source channel', 'single_option', array['Prospector', 'Lead Suggestions', 'Web forms', 'Chatbot', 'Live chat', 'Web visitors', 'Campaigns', 'Marketplace', 'Messaging Inbox']::text[], 37, 'channel', 'enum', 12506, '[{"id": 99, "label": "Prospector"}, {"id": 100, "label": "Lead Suggestions"}, {"id": 101, "label": "Web forms"}, {"id": 102, "label": "Chatbot"}, {"id": 103, "label": "Live chat"}, {"id": 104, "label": "Web visitors"}, {"id": 105, "label": "Campaigns"}, {"id": 106, "label": "Marketplace"}, {"id": 107, "label": "Messaging Inbox"}]'::jsonb),
    ('deal', 'Source channel ID', 'text', '{}'::text[], 38, 'channel_id', 'varchar', 12507, '[]'::jsonb),
    ('deal', 'Archive status', 'single_option', array['Not archived', 'Archived']::text[], 39, 'is_archived', 'enum', 12546, '[{"id": false, "label": "Not archived"}, {"id": true, "label": "Archived"}]'::jsonb),
    ('deal', 'Archive time', 'date', '{}'::text[], 40, 'archive_time', 'date', 12547, '[]'::jsonb),
    ('deal', 'Contact person', 'person_ref', '{}'::text[], 41, 'person_id', 'people', 12461, '[]'::jsonb),
    ('deal', 'Organization', 'organization_ref', '{}'::text[], 42, 'org_id', 'org', 12459, '[]'::jsonb),
    ('deal', 'Sequence enrollment', 'single_option', '{}'::text[], 43, 'sequence_enrollment', 'boolean', 12548, '[]'::jsonb),
    ('deal', 'Value', 'monetary', '{}'::text[], 44, 'value', 'monetary', 12456, '[]'::jsonb),
    ('deal', 'Currency', 'text', '{}'::text[], 45, 'currency', 'varchar', null, '[]'::jsonb),
    ('deal', 'Probability', 'numeric', '{}'::text[], 46, 'probability', 'int', 12458, '[]'::jsonb),
    ('deal', 'Label', 'multi_option', array['Patrocinio CAYENA', '+ 9 CNPJs', '5 a 8 CNPJs', '2 a 4 CNPJs', 'Cliente Difícil', 'Cliente Normal', 'Cliente VIP', 'Shop', 'Compra + 50mil', 'Fornecedor']::text[], 47, 'label', 'set', 12463, '[{"id": 252, "label": "Patrocinio CAYENA"}, {"id": 30, "label": "+ 9 CNPJs"}, {"id": 29, "label": "5 a 8 CNPJs"}, {"id": 31, "label": "2 a 4 CNPJs"}, {"id": 203, "label": "Cliente Difícil"}, {"id": 204, "label": "Cliente Normal"}, {"id": 205, "label": "Cliente VIP"}, {"id": 226, "label": "Shop"}, {"id": 239, "label": "Compra + 50mil"}, {"id": 263, "label": "Fornecedor"}]'::jsonb),
    ('deal', 'Expected close date', 'date', '{}'::text[], 48, 'expected_close_date', 'date', 12484, '[]'::jsonb),
    ('deal', 'Origem do Lead', 'single_option', array['Meta Ads', 'Indicação', 'Prospecção Comercial', 'Site VMarket', 'Parcerias', 'Google Ads', 'Novos CNPJs Base', 'Feiras - Eventos', 'Influencer']::text[], 49, '35b7d222715476c8b0267d90a76ee7ccf65cb7b6', 'enum', 12485, '[{"id": 114, "label": "Meta Ads"}, {"id": 27, "label": "Indicação"}, {"id": 25, "label": "Prospecção Comercial"}, {"id": 24, "label": "Site VMarket"}, {"id": 26, "label": "Parcerias"}, {"id": 94, "label": "Google Ads"}, {"id": 23, "label": "Novos CNPJs Base"}, {"id": 32, "label": "Feiras - Eventos"}, {"id": 233, "label": "Influencer"}]'::jsonb),
    ('deal', 'Indicação Cliente', 'organization_ref', '{}'::text[], 50, '0d76e61d157a4b729b92915bbf3c8c8ea4856ec6', 'org', 12584, '[]'::jsonb),
    ('deal', 'Indicação Externa', 'single_option', array['Antônio Representante', 'Versavel Representante', 'Gass Consultoria', 'Guilherme Medeiros', 'Guilherme Cardeal']::text[], 51, '5e64c9f820adb78f8b2925fee4bbdd27f9fba91d', 'enum', 12540, '[{"id": 122, "label": "Antônio Representante"}, {"id": 123, "label": "Versavel Representante"}, {"id": 124, "label": "Gass Consultoria"}, {"id": 246, "label": "Guilherme Medeiros"}, {"id": 247, "label": "Guilherme Cardeal"}]'::jsonb),
    ('deal', 'Compram mais de 50k/mes?', 'text', '{}'::text[], 52, '95579dceda1c82ef23e7cc4ac51c08d584929342', 'varchar', 12573, '[]'::jsonb),
    ('deal', 'Quantos CNPJs?', 'text', '{}'::text[], 53, '2d85a69bb070d2ad8db81959127fe906c92b9521', 'varchar', 12574, '[]'::jsonb),
    ('deal', 'utm_source', 'text', '{}'::text[], 54, 'f1b6bc80290b31d0e223d727964db76027d3827d', 'varchar', 12496, '[]'::jsonb),
    ('deal', 'utm_medium', 'text', '{}'::text[], 55, '8a44f21e6cf324156d48fe4c823857e2d7fd2ec5', 'varchar', 12497, '[]'::jsonb),
    ('deal', 'utm_campaing', 'text', '{}'::text[], 56, '1392f5b92106c5c53f27c23db70e91e525025a9e', 'varchar', 12498, '[]'::jsonb),
    ('deal', 'utm_content', 'text', '{}'::text[], 57, 'e5d47239621e9988dcefbad16b3a8ae0d99d667c', 'varchar', 12499, '[]'::jsonb),
    ('deal', 'utm_term', 'text', '{}'::text[], 58, 'ab03d4443e21d00227e9f010440718a8dc2ac21a', 'varchar', 12500, '[]'::jsonb),
    ('deal', 'Qual região atende?', 'text', '{}'::text[], 59, '3a6292e42a3f28d9921d8f19b9bc5d4d690806c5', 'varchar', 12580, '[]'::jsonb),
    ('deal', 'Quais categorias de produtos fornece?', 'text', '{}'::text[], 60, '950d51f781336cbd31f3aaaa8dac5b54141cb27b', 'varchar', 12579, '[]'::jsonb),
    ('deal', 'Vencimento do Boleto', 'numeric', '{}'::text[], 61, '9edcc1deb63fbcefd6fdc0d2991ae06a7186a562', 'double', 12591, '[]'::jsonb),
    ('deal', 'Adicionar ao Faturamento da Matriz?', 'single_option', array['Sim', 'Não']::text[], 62, '3cedac69a22710d294ef9116182f9cd3a265acc0', 'enum', 12590, '[{"id": 253, "label": "Sim"}, {"id": 254, "label": "Não"}]'::jsonb),
    ('deal', 'Produto', 'single_option', array['Plataforma de Compras', 'Plataforma de Fornecedor']::text[], 63, 'c9077b11098d76df3179114dbadc51a12cfbea48', 'enum', 12488, '[{"id": 67, "label": "Plataforma de Compras"}, {"id": 68, "label": "Plataforma de Fornecedor"}]'::jsonb),
    ('deal', 'Pagamento', 'single_option', array['Boleto', 'Cartão', 'Depósito ou PIX']::text[], 64, '0c58b01180183c04efb24581c577cc4b464f45ff', 'enum', 12582, '[{"id": 243, "label": "Boleto"}, {"id": 244, "label": "Cartão"}, {"id": 255, "label": "Depósito ou PIX"}]'::jsonb),
    ('deal', 'Faturamento', 'single_option', array['Separado por CNPJ', 'Faturamento Único']::text[], 65, '6326833e27f43780898e702789a89e96ab778cc9', 'enum', 12581, '[{"id": 241, "label": "Separado por CNPJ"}, {"id": 242, "label": "Faturamento Único"}]'::jsonb),
    ('deal', 'Razão Social Principal', 'text', '{}'::text[], 66, 'f363be4577b7b1ad73c3fa8108a389116b5c0635', 'varchar', 12511, '[]'::jsonb),
    ('deal', 'Endereço CNPJ Principal', 'large_text', '{}'::text[], 67, 'cd10f224338182df6eea8ac98da34d0645d737ea', 'text', 12515, '[]'::jsonb),
    ('deal', 'CNPJ Principal', 'text', '{}'::text[], 68, '22e8146e571b84f04631cac22a7439c3b31898fe', 'varchar', 12509, '[]'::jsonb),
    ('deal', 'Quantidade de CNPJs', 'numeric', '{}'::text[], 69, 'e0b823836d4ff5ebe397824d7f0170cd6817ec0a', 'double', 12512, '[]'::jsonb),
    ('deal', 'Período de Fidelidade', 'single_option', array['Mensal', 'Trimestral', 'Semestral', 'Anual']::text[], 70, '2b96fdd368bfb91389a6525a0f272443047191d4', 'enum', 12508, '[{"id": 108, "label": "Mensal"}, {"id": 109, "label": "Trimestral"}, {"id": 110, "label": "Semestral"}, {"id": 111, "label": "Anual"}]'::jsonb),
    ('deal', 'CNPJs Contratados', 'large_text', '{}'::text[], 71, 'b1b00d33bbde9fbc206feb4264bff73285fffa00', 'text', 12513, '[]'::jsonb),
    ('deal', 'Observações', 'text', '{}'::text[], 72, 'a1b7a00ceab5e886d19816ffd4389fd698b54fd2', 'varchar', 12510, '[]'::jsonb),
    ('deal', 'CNPJs Bonificados', 'large_text', '{}'::text[], 73, 'dedecbd4b276a21d13afa88da5c437c235b18eac', 'text', 12585, '[]'::jsonb),
    ('deal', 'Preços ou Emails diferentes por CNPJ', 'large_text', '{}'::text[], 74, 'b214bf66c9392c89770f9c9efa5427a73905a284', 'text', 12587, '[]'::jsonb),
    ('deal', 'Emails pra TODOS Boletos', 'text', '{}'::text[], 75, '1ae7f0c00b7cbe7599ce7052ca7ba3f2849e5ac0', 'varchar', 12586, '[]'::jsonb),
    ('deal', 'Contato do Decisor', 'person_ref', '{}'::text[], 76, '337fe035dcc2bb7580f333262f74e4845dc58211', 'people', 12571, '[]'::jsonb),
    ('deal', 'Responsável', 'single_option', array['Giuliano Palmeira', 'David Gosain', 'Bruno Diniz', 'Rodrigo Fragoso', 'Lucas Bastos', 'Renan Barros', 'Bruno Casteloes', 'Cristiano Ferreira', 'Gustavo Sena']::text[], 77, '48fa8983672755f6b099b760376b3cca9a390fdb', 'enum', 12491, '[{"id": 78, "label": "Giuliano Palmeira"}, {"id": 80, "label": "David Gosain"}, {"id": 81, "label": "Bruno Diniz"}, {"id": 82, "label": "Rodrigo Fragoso"}, {"id": 83, "label": "Lucas Bastos"}, {"id": 84, "label": "Renan Barros"}, {"id": 225, "label": "Bruno Casteloes"}, {"id": 231, "label": "Cristiano Ferreira"}, {"id": 240, "label": "Gustavo Sena"}]'::jsonb),
    ('deal', 'Estado', 'single_option', array['Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará', 'Espírito Santo', 'Goiás', 'Maranhão', 'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Pará', 'Paraíba', 'Paraná', 'Pernambuco', 'Piauí', 'Rio de Janeiro', 'Rio Grande do Norte', 'Rio Grande do Sul', 'Rondônia', 'Roraima', 'Santa Catarina', 'São Paulo', 'Sergipe', 'Tocantins', 'Distrito Federal']::text[], 78, 'afc28ad710ac0f144f69fddab33ee686695ad967', 'enum', 12487, '[{"id": 34, "label": "Acre"}, {"id": 35, "label": "Alagoas"}, {"id": 36, "label": "Amapá"}, {"id": 37, "label": "Amazonas"}, {"id": 38, "label": "Bahia"}, {"id": 39, "label": "Ceará"}, {"id": 40, "label": "Espírito Santo"}, {"id": 41, "label": "Goiás"}, {"id": 42, "label": "Maranhão"}, {"id": 43, "label": "Mato Grosso"}, {"id": 44, "label": "Mato Grosso do Sul"}, {"id": 45, "label": "Minas Gerais"}, {"id": 46, "label": "Pará"}, {"id": 47, "label": "Paraíba"}, {"id": 48, "label": "Paraná"}, {"id": 49, "label": "Pernambuco"}, {"id": 50, "label": "Piauí"}, {"id": 51, "label": "Rio de Janeiro"}, {"id": 52, "label": "Rio Grande do Norte"}, {"id": 53, "label": "Rio Grande do Sul"}, {"id": 54, "label": "Rondônia"}, {"id": 55, "label": "Roraima"}, {"id": 56, "label": "Santa Catarina"}, {"id": 57, "label": "São Paulo"}, {"id": 58, "label": "Sergipe"}, {"id": 59, "label": "Tocantins"}, {"id": 60, "label": "Distrito Federal"}]'::jsonb),
    ('deal', 'C. O que pode tornar a vmarket indispensável pro seu restaurante/ negócio?', 'large_text', '{}'::text[], 79, '83bb9fd018afc469069cb6277049a671877d4e2f', 'text', 12559, '[]'::jsonb),
    ('deal', 'C. Que tipo de comunicação e suporte você espera após o onboarding?', 'large_text', '{}'::text[], 80, '4e33f1e163cd6f1ea768f6c1a5af7221410dc3ad', 'text', 12558, '[]'::jsonb),
    ('deal', 'C. Como você ve o seu dia dia melhorando com Vmarket?', 'large_text', '{}'::text[], 81, '6905c2593b400ceb5491124b6e79bb9048e1ade2', 'text', 12557, '[]'::jsonb),
    ('deal', 'c. Quais seus principais objetivos ao utilizar a vmarket?', 'large_text', '{}'::text[], 82, '3e46530421e06f3e82ce43708b6d681c29aa7fb9', 'text', 12556, '[]'::jsonb),
    ('deal', 'C. Quais são seus maiores desafios na gestão de compras?', 'large_text', '{}'::text[], 83, '5f8ee484acdf942357f989b5b06816bf1df9c2bf', 'text', 12555, '[]'::jsonb),
    ('deal', 'O. Conheceram a plataforma na apresentação comercial?', 'large_text', '{}'::text[], 84, '84e568583d7f3918cc3fe1fddac4e4f117947134', 'text', 12554, '[]'::jsonb),
    ('deal', 'O. Quantas pessoas envolvidas no processo de compras?', 'text', '{}'::text[], 85, 'c3106069fc10a4da4743ca37145949f4dcf42fee', 'varchar', 12553, '[]'::jsonb),
    ('deal', 'O. Quais dias faz compras na semana (quantas vezes)?', 'text', '{}'::text[], 86, '753126d872d3f429045871416884e87399c5c08e', 'varchar', 12552, '[]'::jsonb),
    ('deal', 'O. Qual volume de compras mensal em reais?', 'text', '{}'::text[], 87, '8b9288f02965684ee6ab9046204423b8f2446cbe', 'varchar', 12551, '[]'::jsonb),
    ('deal', 'O. Usam alguma plataforma ou integração no processo de compras?', 'large_text', '{}'::text[], 88, '30a345c0f07074ee16c5a2d37721af0022beae8f', 'text', 12550, '[]'::jsonb),
    ('deal', 'O. Qual seu fluxo de compras?', 'large_text', '{}'::text[], 89, '9cc417f780d27287f441c797469c0f42e20fff30', 'text', 12549, '[]'::jsonb),
    ('deal', '2. Quantos CNPJs pode expandir?', 'numeric', '{}'::text[], 90, '223da6d7a5bc910d75d40a8db74ab18b5dd6fbf5', 'double', 12566, '[]'::jsonb),
    ('deal', '1. Tem possibilidade de expansão de CNPJ?', 'single_option', array['Sim', 'Não']::text[], 91, 'c3cc0e1a1b976329dc886a338067ac3f2da88fcd', 'enum', 12563, '[{"id": 197, "label": "Sim"}, {"id": 198, "label": "Não"}]'::jsonb),
    ('deal', '3. Cliente tem 10 ou + CNPJs?', 'single_option', array['Sim', 'Não']::text[], 92, 'abc629ae29d08a041fe95dec30229f87629b0ce5', 'enum', 12564, '[{"id": 199, "label": "Sim"}, {"id": 200, "label": "Não"}]'::jsonb),
    ('deal', '4. Cliente tem visibilidade no mercado (famoso ou estrategico)?', 'single_option', array['Sim', 'Não']::text[], 93, 'dad9e393d2113fa5d71877c8171f141b0280fff5', 'enum', 12565, '[{"id": 201, "label": "Sim"}, {"id": 202, "label": "Não"}]'::jsonb),
    ('deal', '1. Não entregou as listas em 1 semana?', 'single_option', array['Sim', 'Não']::text[], 94, '8eeb4cbed753c2c2832518e539cf869bcc2b5be4', 'enum', 12560, '[{"id": 191, "label": "Sim"}, {"id": 192, "label": "Não"}]'::jsonb),
    ('deal', '2. Comprador sozinho?', 'single_option', array['Sim', 'Não']::text[], 95, '338a7007a8908ee3d231663c89e0cd58aaed18ed', 'enum', 12561, '[{"id": 193, "label": "Sim"}, {"id": 194, "label": "Não"}]'::jsonb),
    ('deal', '3. Comprador tem dificuldade com tecnologia?', 'single_option', array['Sim', 'Não']::text[], 96, '57bed72e905b2a6ae2cbb767ead4699197987632', 'enum', 12562, '[{"id": 195, "label": "Sim"}, {"id": 196, "label": "Não"}]'::jsonb),
    ('deal', 'Feedback Primeira Compra', 'large_text', '{}'::text[], 97, 'aeddf0b3481aeda954effd39c793325c610834cb', 'text', 12522, '[]'::jsonb),
    ('deal', 'Vendedor', 'user_ref', '{}'::text[], 98, '7653f42b2da8e64ab44f4888053dd6be9079a116', 'user', 12521, '[]'::jsonb),
    ('deal', 'Data 1º Envio - Reativação', 'date', '{}'::text[], 99, 'cedb5b129a6ea3ccd5f4930b393a0e9245d1d71e', 'date', 12537, '[]'::jsonb),
    ('deal', 'Data 1ª Resposta - Reativação', 'date', '{}'::text[], 100, '1b542064fcecec7846ffe6f1ab8549a5d9c355ba', 'date', 12538, '[]'::jsonb),
    ('deal', 'Resultado - Reativação', 'single_option', array['Sem perfil de cliente', 'Não tem interesse', 'Usa concorrente', 'Cliente não respondeu mais', 'Outro (escrever na nota)', 'Nova Oportunidade (reunião agendada)']::text[], 101, '6bbdcd23f9ccecc08e9bb6f0d7bb58e04d996cea', 'enum', 12539, '[{"id": 116, "label": "Sem perfil de cliente"}, {"id": 117, "label": "Não tem interesse"}, {"id": 118, "label": "Usa concorrente"}, {"id": 119, "label": "Cliente não respondeu mais"}, {"id": 120, "label": "Outro (escrever na nota)"}, {"id": 121, "label": "Nova Oportunidade (reunião agendada)"}]'::jsonb),
    ('deal', 'Ct.Trativa Cancelamento Giuliano', 'large_text', '{}'::text[], 102, 'f5c14696e862aab2264d514203c46866bd945169', 'text', 12536, '[]'::jsonb),
    ('deal', 'Ct.Data do Cancelamento Efetivo', 'date', '{}'::text[], 103, 'dc1b13dc34279fcce9249ed66a6489b2bdab28bc', 'date', 12534, '[]'::jsonb),
    ('deal', 'Ct.Data do Pedido de Cancelamento', 'date', '{}'::text[], 104, '1e4113278d1554549928cd90e54c0506d39bef2f', 'date', 12533, '[]'::jsonb),
    ('deal', 'Ct.6. Pode deixar um comentário, feedback ou sugestão?', 'text', '{}'::text[], 105, '57241f6230fb20e138543edf51f420a611029d4b', 'varchar', 12532, '[]'::jsonb),
    ('deal', 'Ct.5. Você considera voltar a usar a VMarket no futuro?', 'text', '{}'::text[], 106, 'c3dc34bed839a441fa3ddc96bc56b2d09a4568ad', 'varchar', 12531, '[]'::jsonb),
    ('deal', 'Ct.4. O que você mais gosta na VMarket?', 'text', '{}'::text[], 107, '24758655b215078ebc7cb60e7d65148d83cc963e', 'varchar', 12530, '[]'::jsonb),
    ('deal', 'Ct.3. Com que frequência você usa a VMarket?', 'text', '{}'::text[], 108, '9218cbe0b2b89739f163dd48e28aa0f62043b941', 'varchar', 12529, '[]'::jsonb),
    ('deal', 'Ct.2. O que faria você reconsiderar o cancelamento?', 'text', '{}'::text[], 109, '050c7e13466a2cb6f361f4cd505a50b1a3fe6fe7', 'varchar', 12528, '[]'::jsonb),
    ('deal', 'Ct.1. Por que você decidiu cancelar?', 'text', '{}'::text[], 110, 'abe39c322e3279e4c21eca6acf032b259571d52f', 'varchar', 12527, '[]'::jsonb),
    ('deal', 'Data Transferência pra Vendas - Reunião', 'date', '{}'::text[], 111, '10ba7b1d9e77d8c87d9d695cf80a747c40afde27', 'date', 12578, '[]'::jsonb),
    ('deal', 'SDR', 'user_ref', '{}'::text[], 112, '53d44411b1255ad360ee98d5ca6ae8ea3e186c2e', 'user', 12577, '[]'::jsonb),
    ('deal', 'Tipo de Suporte', 'single_option', array['1. Dúvida de Configuração ou Uso (Suporte)', '2. Problema Técnicos (TI)', '3. Problema de Usabilidade (UX)', '4. Solicitação de Melhoria ou Funcionalidades (TI)', '5. Problema de Integração/ API (TI)', '6. Feedback do Produto (TI)', '7. Suporte com Conta (Suporte)', '8. Suporte com Faturamento (Financeiro)']::text[], 113, 'bdccec38847b30246d707ecfabb4a4ed74c35885', 'enum', 12541, '[{"id": 127, "label": "1. Dúvida de Configuração ou Uso (Suporte)"}, {"id": 128, "label": "2. Problema Técnicos (TI)"}, {"id": 129, "label": "3. Problema de Usabilidade (UX)"}, {"id": 130, "label": "4. Solicitação de Melhoria ou Funcionalidades (TI)"}, {"id": 131, "label": "5. Problema de Integração/ API (TI)"}, {"id": 132, "label": "6. Feedback do Produto (TI)"}, {"id": 133, "label": "7. Suporte com Conta (Suporte)"}, {"id": 134, "label": "8. Suporte com Faturamento (Financeiro)"}]'::jsonb),
    ('deal', 'Área da Plataforma para Suporte', 'multi_option', array['C.Dashboard', 'C.Compras/Meus pedidos', 'C.Compras/Cadastrar pedido manual', 'C.Compras/Histórico de compras', 'C.Compras/Curva ABC', 'C.Cotações/Meus produtos', 'C.Cotações/Analise de preços válidos', 'C.Cotações/Minhas cotações', 'C.Cotações/Meus fornecedores', 'C.Cotações/Minhas seções', 'C.Cotações/Requisições/Cadastrar', 'C.Cotações/Requisições/Abertas', 'C. Cotações/Requisições/Histórico', 'C.Cotações/Requisições/Agendamento', 'C.Cotações/Requisições/Extrato WhatsApp', 'C.Cotações/Configurar filiais/produtos', 'C.Cotações/Exportar lista de produtos', 'C.Cotações/Exportar lista de fornecedores', 'C.Estoque/Histórico', 'C.Estoque/Configurações', 'C.Estoque/Minhas Contagens', 'C.Orçamento/ Config. Orçamento', 'C. Orçamento/ Desvio Padrão', 'C.Financeiro/Minhas notas fiscais', 'C.Conta do Cliente', 'C.Extensão do Chrome', 'C.Aplicativo', 'C.Sistema integrado a Vmarket', 'F.Dashboard', 'F.Cotações/Minhas cotações', 'F.Cotações/Cotações pra participar', 'F.Clientes', 'F.Pedidos', 'F.Produtos', 'F.Vendedores', 'F.Configurações', 'F.Conta do Cliente', 'NA']::text[], 114, '588f99b2e1d852f8b1ce58379034e501505c195d', 'set', 12542, '[{"id": 164, "label": "C.Dashboard"}, {"id": 135, "label": "C.Compras/Meus pedidos"}, {"id": 136, "label": "C.Compras/Cadastrar pedido manual"}, {"id": 137, "label": "C.Compras/Histórico de compras"}, {"id": 138, "label": "C.Compras/Curva ABC"}, {"id": 139, "label": "C.Cotações/Meus produtos"}, {"id": 165, "label": "C.Cotações/Analise de preços válidos"}, {"id": 140, "label": "C.Cotações/Minhas cotações"}, {"id": 141, "label": "C.Cotações/Meus fornecedores"}, {"id": 142, "label": "C.Cotações/Minhas seções"}, {"id": 144, "label": "C.Cotações/Requisições/Cadastrar"}, {"id": 145, "label": "C.Cotações/Requisições/Abertas"}, {"id": 146, "label": "C. Cotações/Requisições/Histórico"}, {"id": 147, "label": "C.Cotações/Requisições/Agendamento"}, {"id": 148, "label": "C.Cotações/Requisições/Extrato WhatsApp"}, {"id": 149, "label": "C.Cotações/Configurar filiais/produtos"}, {"id": 150, "label": "C.Cotações/Exportar lista de produtos"}, {"id": 151, "label": "C.Cotações/Exportar lista de fornecedores"}, {"id": 152, "label": "C.Estoque/Histórico"}, {"id": 153, "label": "C.Estoque/Configurações"}, {"id": 154, "label": "C.Estoque/Minhas Contagens"}, {"id": 177, "label": "C.Orçamento/ Config. Orçamento"}, {"id": 178, "label": "C. Orçamento/ Desvio Padrão"}, {"id": 175, "label": "C.Financeiro/Minhas notas fiscais"}, {"id": 163, "label": "C.Conta do Cliente"}, {"id": 155, "label": "C.Extensão do Chrome"}, {"id": 156, "label": "C.Aplicativo"}, {"id": 157, "label": "C.Sistema integrado a Vmarket"}, {"id": 166, "label": "F.Dashboard"}, {"id": 167, "label": "F.Cotações/Minhas cotações"}, {"id": 168, "label": "F.Cotações/Cotações pra participar"}, {"id": 169, "label": "F.Clientes"}, {"id": 170, "label": "F.Pedidos"}, {"id": 171, "label": "F.Produtos"}, {"id": 172, "label": "F.Vendedores"}, {"id": 173, "label": "F.Configurações"}, {"id": 174, "label": "F.Conta do Cliente"}, {"id": 158, "label": "NA"}]'::jsonb),
    ('deal', 'Descrição do Suporte', 'large_text', '{}'::text[], 115, '884c7b012ae37a6e6a419e0579879803f6570f74', 'text', 12543, '[]'::jsonb),
    ('deal', 'Nível de Severidade (SLA)', 'single_option', array['Crítica (S1) - 4 horas', 'Alta (S2) - 1 dia', 'Média (S3) - 3 a 5 dias', 'Baixa (S4) - de acordo com roadmap']::text[], 116, '480973dc9101e4dbc0131b8b39b65313895f80e4', 'enum', 12544, '[{"id": 159, "label": "Crítica (S1) - 4 horas"}, {"id": 160, "label": "Alta (S2) - 1 dia"}, {"id": 161, "label": "Média (S3) - 3 a 5 dias"}, {"id": 162, "label": "Baixa (S4) - de acordo com roadmap"}]'::jsonb),
    ('deal', 'Etapa Negócio Fechado', 'single_option', array['SIm']::text[], 117, 'b6c34537385989b13f8b21f56aa6650405f5a1dc', 'enum', 12583, '[{"id": 245, "label": "SIm"}]'::jsonb),
    ('deal', 'Data Último Contato', 'date', '{}'::text[], 118, 'c2960d60e3faa15c978bc45ff8cd4dcdafdaadda', 'date', 12588, '[]'::jsonb),
    ('deal', 'Situação Último Contato', 'large_text', '{}'::text[], 119, '158a6b7a8699c3b1fd45565c654bb3a466e77e96', 'text', 12589, '[]'::jsonb),
    ('person', 'ID', 'numeric', '{}'::text[], 1, 'id', 'int', 9051, '[]'::jsonb),
    ('person', 'Name', 'text', '{}'::text[], 2, 'name', 'varchar', 9039, '[]'::jsonb),
    ('person', 'Label', 'single_option', array['Cliente', 'Lead quente', 'Lead morno', 'Lead frio', 'Interessado', 'Respondeu', 'Tentando Contato', 'Sem Interesse', 'Ex-Cliente', 'Mudou de Emprego', 'Não Responde', 'Não Contactar', 'Dados Errados']::text[], 3, 'label', 'enum', 9040, '[{"id": 5, "label": "Cliente"}, {"id": 6, "label": "Lead quente"}, {"id": 7, "label": "Lead morno"}, {"id": 8, "label": "Lead frio"}, {"id": 214, "label": "Interessado"}, {"id": 213, "label": "Respondeu"}, {"id": 212, "label": "Tentando Contato"}, {"id": 211, "label": "Sem Interesse"}, {"id": 215, "label": "Ex-Cliente"}, {"id": 216, "label": "Mudou de Emprego"}, {"id": 210, "label": "Não Responde"}, {"id": 218, "label": "Não Contactar"}, {"id": 217, "label": "Dados Errados"}]'::jsonb),
    ('person', 'Phone', 'phone', '{}'::text[], 4, 'phone', 'phone', 9041, '[]'::jsonb),
    ('person', 'Email', 'text', '{}'::text[], 5, 'email', 'varchar', 9042, '[]'::jsonb),
    ('person', 'Person created', 'date', '{}'::text[], 6, 'add_time', 'date', 9043, '[]'::jsonb),
    ('person', 'Update time', 'date', '{}'::text[], 7, 'update_time', 'date', 9044, '[]'::jsonb),
    ('person', 'Organization', 'organization_ref', '{}'::text[], 8, 'org_id', 'org', 9045, '[]'::jsonb),
    ('person', 'Owner', 'user_ref', '{}'::text[], 9, 'owner_id', 'user', 9046, '[]'::jsonb),
    ('person', 'Open deals', 'numeric', '{}'::text[], 10, 'open_deals_count', 'double', 9047, '[]'::jsonb),
    ('person', 'Visible to', 'single_option', array['Item owner', 'All users']::text[], 11, 'visible_to', 'visible_to', 9048, '[{"id": 1, "label": "Item owner"}, {"id": 3, "label": "All users"}]'::jsonb),
    ('person', 'Next activity date', 'date', '{}'::text[], 12, 'next_activity_date', 'date', 9049, '[]'::jsonb),
    ('person', 'Last activity date', 'date', '{}'::text[], 13, 'last_activity_date', 'date', 9050, '[]'::jsonb),
    ('person', 'Won deals', 'numeric', '{}'::text[], 14, 'won_deals_count', 'int', 9052, '[]'::jsonb),
    ('person', 'Lost deals', 'numeric', '{}'::text[], 15, 'lost_deals_count', 'int', 9053, '[]'::jsonb),
    ('person', 'Closed deals', 'numeric', '{}'::text[], 16, 'closed_deals_count', 'int', 9054, '[]'::jsonb),
    ('person', 'Total activities', 'numeric', '{}'::text[], 17, 'activities_count', 'int', 9055, '[]'::jsonb),
    ('person', 'Done activities', 'numeric', '{}'::text[], 18, 'done_activities_count', 'int', 9056, '[]'::jsonb),
    ('person', 'Activities to do', 'numeric', '{}'::text[], 19, 'undone_activities_count', 'int', 9057, '[]'::jsonb),
    ('person', 'Email messages count', 'numeric', '{}'::text[], 20, 'email_messages_count', 'int', 9058, '[]'::jsonb),
    ('person', 'Profile picture', 'text', '{}'::text[], 21, 'picture_id', 'picture', 9059, '[]'::jsonb),
    ('person', 'Last email received', 'date', '{}'::text[], 22, 'last_incoming_mail_time', 'date', 9060, '[]'::jsonb),
    ('person', 'Last email sent', 'date', '{}'::text[], 23, 'last_outgoing_mail_time', 'date', 9061, '[]'::jsonb),
    ('person', 'First name', 'text', '{}'::text[], 24, 'first_name', 'varchar', 9064, '[]'::jsonb),
    ('person', 'Last name', 'text', '{}'::text[], 25, 'last_name', 'varchar', 9065, '[]'::jsonb),
    ('person', 'Labels', 'multi_option', array['Cliente', 'Lead quente', 'Lead morno', 'Lead frio', 'Interessado', 'Respondeu', 'Tentando Contato', 'Sem Interesse', 'Ex-Cliente', 'Mudou de Emprego', 'Não Responde', 'Não Contactar', 'Dados Errados']::text[], 26, 'label_ids', 'set', 9072, '[{"id": 5, "label": "Cliente"}, {"id": 6, "label": "Lead quente"}, {"id": 7, "label": "Lead morno"}, {"id": 8, "label": "Lead frio"}, {"id": 214, "label": "Interessado"}, {"id": 213, "label": "Respondeu"}, {"id": 212, "label": "Tentando Contato"}, {"id": 211, "label": "Sem Interesse"}, {"id": 215, "label": "Ex-Cliente"}, {"id": 216, "label": "Mudou de Emprego"}, {"id": 210, "label": "Não Responde"}, {"id": 218, "label": "Não Contactar"}, {"id": 217, "label": "Dados Errados"}]'::jsonb),
    ('person', 'Cargo', 'text', '{}'::text[], 27, 'afd574ed8ff95c4ce19a8aba6fb4ce0be977801d', 'varchar', 9066, '[]'::jsonb),
    ('person', 'utm_source', 'text', '{}'::text[], 28, '421b8eb91a49f03a7cb05d3b35161077b5e88d8f', 'varchar', 9067, '[]'::jsonb),
    ('person', 'utm_medium', 'text', '{}'::text[], 29, '6a3b8b12f52c92c5c5b86e1a1e6018a0f2db1447', 'varchar', 9068, '[]'::jsonb),
    ('person', 'utm_campaign', 'text', '{}'::text[], 30, '0f04f85ad114e18bd1d984270ac2e1c25631c0fb', 'varchar', 9069, '[]'::jsonb),
    ('person', 'utm_content', 'text', '{}'::text[], 31, 'adda7a649f74b89d2674c746f347b827eb7e7539', 'varchar', 9070, '[]'::jsonb),
    ('person', 'utm_term', 'text', '{}'::text[], 32, 'c5cbc0c43bd70646f48f0c93d3adf3d7bb1722ab', 'varchar', 9071, '[]'::jsonb),
    ('person', 'Whatsapp chat link', 'text', '{}'::text[], 33, '252b7121112a7fce82bdb7fe4f9a65ec5af662a6', 'varchar', 9074, '[]'::jsonb),
    ('person', 'LinkedIn', 'text', '{}'::text[], 34, 'dfb14833946ca025c548ac054e933753a81a8923', 'varchar', 9075, '[]'::jsonb),
    ('person', 'Cidade', 'text', '{}'::text[], 35, '45c8613a2f233bac3b459c5c0cd3a610c9e142c4', 'varchar', 9076, '[]'::jsonb),
    ('person', 'Estado', 'text', '{}'::text[], 36, '1297680c50bb31b4226c5084fc35bf268815c636', 'varchar', 9077, '[]'::jsonb),
    ('organization', 'ID', 'numeric', '{}'::text[], 1, 'id', 'int', 4012, '[]'::jsonb),
    ('organization', 'Name', 'text', '{}'::text[], 2, 'name', 'varchar', 4002, '[]'::jsonb),
    ('organization', 'Label', 'single_option', array['Cliente', 'Lead quente', 'Lead morno', 'Lead frio', 'Oportunidade Ativa', 'Oportunidade Morta', 'Ex-Cliente', 'Não Prospectar', 'Sem Contato', 'Representante', 'Vendas BPO', 'Implantação BPO', 'Consultoria BPO', 'Compras BPO', 'Acesso Pipedrive', 'Acesso CRM BPO']::text[], 3, 'label', 'enum', 4003, '[{"id": 1, "label": "Cliente"}, {"id": 2, "label": "Lead quente"}, {"id": 3, "label": "Lead morno"}, {"id": 4, "label": "Lead frio"}, {"id": 219, "label": "Oportunidade Ativa"}, {"id": 220, "label": "Oportunidade Morta"}, {"id": 222, "label": "Ex-Cliente"}, {"id": 221, "label": "Não Prospectar"}, {"id": 223, "label": "Sem Contato"}, {"id": 256, "label": "Representante"}, {"id": 260, "label": "Vendas BPO"}, {"id": 261, "label": "Implantação BPO"}, {"id": 262, "label": "Consultoria BPO"}, {"id": 259, "label": "Compras BPO"}, {"id": 257, "label": "Acesso Pipedrive"}, {"id": 258, "label": "Acesso CRM BPO"}]'::jsonb),
    ('organization', 'Owner', 'user_ref', '{}'::text[], 4, 'owner_id', 'user', 4004, '[]'::jsonb),
    ('organization', 'People', 'numeric', '{}'::text[], 5, 'people_count', 'double', 4005, '[]'::jsonb),
    ('organization', 'Open deals', 'numeric', '{}'::text[], 6, 'open_deals_count', 'double', 4006, '[]'::jsonb),
    ('organization', 'Organization created', 'date', '{}'::text[], 7, 'add_time', 'date', 4007, '[]'::jsonb),
    ('organization', 'Update time', 'date', '{}'::text[], 8, 'update_time', 'date', 4008, '[]'::jsonb),
    ('organization', 'Visible to', 'single_option', array['Item owner', 'All users']::text[], 9, 'visible_to', 'visible_to', 4009, '[{"id": 1, "label": "Item owner"}, {"id": 3, "label": "All users"}]'::jsonb),
    ('organization', 'Next activity date', 'date', '{}'::text[], 10, 'next_activity_date', 'date', 4010, '[]'::jsonb),
    ('organization', 'Last activity date', 'date', '{}'::text[], 11, 'last_activity_date', 'date', 4011, '[]'::jsonb),
    ('organization', 'Won deals', 'numeric', '{}'::text[], 12, 'won_deals_count', 'int', 4013, '[]'::jsonb),
    ('organization', 'Lost deals', 'numeric', '{}'::text[], 13, 'lost_deals_count', 'int', 4014, '[]'::jsonb),
    ('organization', 'Closed deals', 'numeric', '{}'::text[], 14, 'closed_deals_count', 'int', 4015, '[]'::jsonb),
    ('organization', 'Total activities', 'numeric', '{}'::text[], 15, 'activities_count', 'int', 4016, '[]'::jsonb),
    ('organization', 'Done activities', 'numeric', '{}'::text[], 16, 'done_activities_count', 'int', 4017, '[]'::jsonb),
    ('organization', 'Activities to do', 'numeric', '{}'::text[], 17, 'undone_activities_count', 'int', 4018, '[]'::jsonb),
    ('organization', 'Email messages count', 'numeric', '{}'::text[], 18, 'email_messages_count', 'int', 4019, '[]'::jsonb),
    ('organization', 'Profile picture', 'text', '{}'::text[], 19, 'picture_id', 'picture', 4020, '[]'::jsonb),
    ('organization', 'Website', 'text', '{}'::text[], 20, 'website', 'varchar', 4044, '[]'::jsonb),
    ('organization', 'LinkedIn profile', 'text', '{}'::text[], 21, 'linkedin', 'varchar', 4045, '[]'::jsonb),
    ('organization', 'Industry', 'single_option', array['Accommodation services', 'Administrative and support services', 'Construction', 'Consumer services', 'Education', 'Entertainment providers', 'Farming, ranching, forestry', 'Financial services', 'Government administration', 'Holding companies', 'Hospitals and health care', 'Manufacturing', 'Oil, gas, and mining', 'Professional services', 'Real estate and equipment rental services', 'Retail', 'Technology, information and media', 'Transportation, logistics, supply chain and storage', 'Utilities', 'Wholesale']::text[], 22, 'industry', 'enum', 4046, '[{"id": 1, "label": "Accommodation services"}, {"id": 2, "label": "Administrative and support services"}, {"id": 3, "label": "Construction"}, {"id": 4, "label": "Consumer services"}, {"id": 5, "label": "Education"}, {"id": 6, "label": "Entertainment providers"}, {"id": 7, "label": "Farming, ranching, forestry"}, {"id": 8, "label": "Financial services"}, {"id": 9, "label": "Government administration"}, {"id": 10, "label": "Holding companies"}, {"id": 11, "label": "Hospitals and health care"}, {"id": 12, "label": "Manufacturing"}, {"id": 13, "label": "Oil, gas, and mining"}, {"id": 14, "label": "Professional services"}, {"id": 15, "label": "Real estate and equipment rental services"}, {"id": 16, "label": "Retail"}, {"id": 17, "label": "Technology, information and media"}, {"id": 18, "label": "Transportation, logistics, supply chain and storage"}, {"id": 19, "label": "Utilities"}, {"id": 20, "label": "Wholesale"}]'::jsonb),
    ('organization', 'Annual revenue', 'single_option', array['0', '1 - 10M USD', '10 - 100M USD', '100 - 1000M USD', '1 - 10B USD', '10+B USD']::text[], 23, 'annual_revenue', 'enum', 4047, '[{"id": 1, "label": "0"}, {"id": 2, "label": "1 - 10M USD"}, {"id": 3, "label": "10 - 100M USD"}, {"id": 4, "label": "100 - 1000M USD"}, {"id": 5, "label": "1 - 10B USD"}, {"id": 6, "label": "10+B USD"}]'::jsonb),
    ('organization', 'Number of employees', 'numeric', '{}'::text[], 24, 'employee_count', 'int', 4048, '[]'::jsonb),
    ('organization', 'Login do Cliente', 'text', '{}'::text[], 25, '75febbe153484f54ccf121b75678fd119c346556', 'varchar', 4043, '[]'::jsonb),
    ('organization', 'Tipo de Login do Usuário', 'single_option', array['Login simples', 'Login de pré-cotação (centralizada)', 'Login Fornecedor']::text[], 26, '565770fb6c67f6fe7052e8dc14972b02accc7d9f', 'enum', 4042, '[{"id": 125, "label": "Login simples"}, {"id": 126, "label": "Login de pré-cotação (centralizada)"}, {"id": 176, "label": "Login Fornecedor"}]'::jsonb),
    ('organization', 'Address', 'address', '{}'::text[], 27, 'address', 'address', 4021, '[]'::jsonb),
    ('organization', 'Latitude of Address', 'numeric', '{}'::text[], 28, 'address_lat', 'double', null, '[]'::jsonb),
    ('organization', 'Longitude of Address', 'numeric', '{}'::text[], 29, 'address_long', 'double', null, '[]'::jsonb),
    ('organization', 'Apartment/suite no of Address', 'text', '{}'::text[], 30, 'address_subpremise', 'varchar', null, '[]'::jsonb),
    ('organization', 'House number of Address', 'text', '{}'::text[], 31, 'address_street_number', 'varchar', null, '[]'::jsonb),
    ('organization', 'Street/road name of Address', 'text', '{}'::text[], 32, 'address_route', 'varchar', null, '[]'::jsonb),
    ('organization', 'District/sublocality of Address', 'text', '{}'::text[], 33, 'address_sublocality', 'varchar', null, '[]'::jsonb),
    ('organization', 'City/town/village/locality of Address', 'text', '{}'::text[], 34, 'address_locality', 'varchar', null, '[]'::jsonb),
    ('organization', 'State/county of Address', 'text', '{}'::text[], 35, 'address_admin_area_level_1', 'varchar', null, '[]'::jsonb),
    ('organization', 'Region of Address', 'text', '{}'::text[], 36, 'address_admin_area_level_2', 'varchar', null, '[]'::jsonb),
    ('organization', 'Country of Address', 'text', '{}'::text[], 37, 'address_country', 'varchar', null, '[]'::jsonb),
    ('organization', 'ZIP/Postal code of Address', 'text', '{}'::text[], 38, 'address_postal_code', 'varchar', null, '[]'::jsonb),
    ('organization', 'Full/combined address of Address', 'text', '{}'::text[], 39, 'address_formatted_address', 'varchar', null, '[]'::jsonb),
    ('organization', 'Labels', 'multi_option', array['Cliente', 'Lead quente', 'Lead morno', 'Lead frio', 'Oportunidade Ativa', 'Oportunidade Morta', 'Ex-Cliente', 'Não Prospectar', 'Sem Contato', 'Representante', 'Vendas BPO', 'Implantação BPO', 'Consultoria BPO', 'Compras BPO', 'Acesso Pipedrive', 'Acesso CRM BPO']::text[], 40, 'label_ids', 'set', 4040, '[{"id": 1, "label": "Cliente"}, {"id": 2, "label": "Lead quente"}, {"id": 3, "label": "Lead morno"}, {"id": 4, "label": "Lead frio"}, {"id": 219, "label": "Oportunidade Ativa"}, {"id": 220, "label": "Oportunidade Morta"}, {"id": 222, "label": "Ex-Cliente"}, {"id": 221, "label": "Não Prospectar"}, {"id": 223, "label": "Sem Contato"}, {"id": 256, "label": "Representante"}, {"id": 260, "label": "Vendas BPO"}, {"id": 261, "label": "Implantação BPO"}, {"id": 262, "label": "Consultoria BPO"}, {"id": 259, "label": "Compras BPO"}, {"id": 257, "label": "Acesso Pipedrive"}, {"id": 258, "label": "Acesso CRM BPO"}]'::jsonb),
    ('organization', 'Produto.', 'single_option', array['Comprador', 'Fornecedor']::text[], 41, '6329a10a4162ecb13d210b9454f4598c3de43762', 'enum', 4022, '[{"id": 15, "label": "Comprador"}, {"id": 16, "label": "Fornecedor"}]'::jsonb),
    ('organization', 'Tipo de Cliente', 'single_option', array['Bares e Restaurantes', 'Hotéis', 'Padarias', 'Pequena Indústria', 'Grande Indústria', 'Distribuidor']::text[], 42, 'c8a0499b420080755cbbaaea3007a467d6f76300', 'enum', 4023, '[{"id": 17, "label": "Bares e Restaurantes"}, {"id": 18, "label": "Hotéis"}, {"id": 19, "label": "Padarias"}, {"id": 20, "label": "Pequena Indústria"}, {"id": 21, "label": "Grande Indústria"}, {"id": 22, "label": "Distribuidor"}]'::jsonb),
    ('organization', 'Lista', 'text', '{}'::text[], 43, '383f0b1826f0b56ee0742b4bdad58425d78fd14c', 'varchar', 4024, '[]'::jsonb),
    ('organization', 'Classificação Lista', 'text', '{}'::text[], 44, '937057cf34dc0ee1f6bce6505a73a24fe185596c', 'varchar', 4025, '[]'::jsonb),
    ('organization', 'Telefone', 'phone', '{}'::text[], 45, '930a8647cfd0cc106ea501b7efbaee45039a5adf', 'phone', 4027, '[]'::jsonb),
    ('organization', 'Email', 'text', '{}'::text[], 46, '2ae2d51d053c468ac2b0a2678cf357ab0ed2c90c', 'varchar', 4033, '[]'::jsonb),
    ('organization', 'Celular', 'phone', '{}'::text[], 47, '0478dd808108fceebb17125354cbdb5ca37fd141', 'phone', 4034, '[]'::jsonb),
    ('organization', 'utm_source', 'text', '{}'::text[], 48, '2f68cabf61f2dfc3a85dad8a3263bf091d7043a8', 'varchar', 4035, '[]'::jsonb),
    ('organization', 'utm_medium', 'text', '{}'::text[], 49, 'acaa82b49a99dfbda446d5cd4aa6a07200b6aef6', 'varchar', 4036, '[]'::jsonb),
    ('organization', 'utm_campaign', 'text', '{}'::text[], 50, '23afc3425f39a6a1f55f8f2ba954ad761e7f1d41', 'varchar', 4037, '[]'::jsonb),
    ('organization', 'utm_content', 'text', '{}'::text[], 51, '0e32b8ed3ed7d58c511aeef6c132b3a87340cc1e', 'varchar', 4038, '[]'::jsonb),
    ('organization', 'utm_term', 'text', '{}'::text[], 52, 'fd1344d357323dd8e54c8231dea7f5138df4c7e3', 'varchar', 4039, '[]'::jsonb),
    ('organization', 'codigo_cliente_omie', 'text', '{}'::text[], 53, '7341372b1cf6e0b5f6e29c5616939369a898802a', 'varchar', 4049, '[]'::jsonb)
)
insert into public.custom_fields (entity, name, field_type, options, sort_order, pipedrive_key, pipedrive_field_type, pipedrive_id, pipedrive_options)
select entity, name, field_type::public.field_type, options, sort_order, pipedrive_key, pipedrive_field_type, pipedrive_id, pipedrive_options
from pipedrive_fields
on conflict (entity, pipedrive_key) where pipedrive_key is not null do update set
  name = excluded.name,
  field_type = excluded.field_type,
  options = excluded.options,
  sort_order = excluded.sort_order,
  pipedrive_field_type = excluded.pipedrive_field_type,
  pipedrive_id = excluded.pipedrive_id,
  pipedrive_options = excluded.pipedrive_options;
